<a href="https://colab.research.google.com/github/ianuvrat/NLP/blob/main/NLP_8_Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
# Libraries USed Tensorflow> 2.0  and keras

##tensorflow >2.0

In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:

### sentences                                                #initializing sentences
sent=[  'the glass of milk and sugar',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk and sugar',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=10000

One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]       #getting index from dictionary by passing 'word' in 'vocab size'
print(onehot_repr)

[[8817, 5545, 6569, 6818, 7452, 1393], [8817, 5545, 6569, 383], [8817, 6606, 6569, 1889], [3730, 537, 8548, 8432, 9057], [3730, 537, 8548, 8432, 326], [5409, 8817, 990, 6569, 1343], [9441, 2316, 3673, 8432]]


Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding                              #Embedding layer
from tensorflow.keras.preprocessing.sequence import pad_sequences          #Padding 0's beforethe numbers
from tensorflow.keras.models import Sequential                             #Sequential layer
import numpy as np

In [ ]:
sent_length=8                                                              #Length of sentence
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)  #Introducing 0's beforehand
print(embedded_docs)

[[   0    0 8817 5545 6569 6818 7452 1393]
 [   0    0    0    0 8817 5545 6569  383]
 [   0    0    0    0 8817 6606 6569 1889]
 [   0    0    0 3730  537 8548 8432 9057]
 [   0    0    0 3730  537 8548 8432  326]
 [   0    0    0 5409 8817  990 6569 1343]
 [   0    0    0    0 9441 2316 3673 8432]]


In [ ]:
dim=10                                                                 #intitalizing dimensions (or features size)

In [ ]:
model=Sequential()                                                     #initializing Sequential Layer
model.add(Embedding(voc_size,dim,input_length=sent_length))             #vocabulary size, dimension, sentence length
model.compile('adam','mse')                                            #compiling using 'adam' optimizer and performance metrics is Mean Square Error

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(embedded_docs[5] , embedded_docs[5][5])

[   0    0    0 5409 8817  990 6569 1343] 990


Lets see how we converted words into vectors

In [ ]:
print(model.predict(embedded_docs[5]))                        #Representing  ---[0    0    0 5409 8817  990 6569 1343]--- as vectors with features(dimension = 10)

[[[-0.02767271  0.03654594  0.04781513 -0.02667452  0.02255342
    0.00054307 -0.03754883 -0.01010317 -0.00422139 -0.02576688]]

 [[-0.02767271  0.03654594  0.04781513 -0.02667452  0.02255342
    0.00054307 -0.03754883 -0.01010317 -0.00422139 -0.02576688]]

 [[-0.02767271  0.03654594  0.04781513 -0.02667452  0.02255342
    0.00054307 -0.03754883 -0.01010317 -0.00422139 -0.02576688]]

 [[-0.01499424  0.0483135  -0.00327692  0.01478418  0.01499564
   -0.02055746  0.01056106 -0.03667369  0.04790041  0.03533003]]

 [[ 0.03208775  0.01613034  0.00478371 -0.00219892  0.01611746
    0.00046384  0.03118363  0.03733644  0.01539323  0.02085376]]

 [[ 0.01264114  0.01524791 -0.04914062  0.04310412  0.03832993
   -0.03637781  0.0491089  -0.03810269  0.01335784  0.01907948]]

 [[ 0.00735407 -0.04406775 -0.04610842 -0.04319939  0.00202365
   -0.03933302 -0.03061906  0.03929127  0.03564714  0.03536775]]

 [[-0.04039457  0.01517984  0.04057181  0.01157935  0.00515429
   -0.01689434  0.03534528  0.0479